export CUDA_VISIBLE_DEVICES=1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/global_wind/ \
  --data_path None \
  --model_id global_wind_48_6_iTransformer \
  --model iTransformer \
  --data Global_Wind \
  --features M \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 6 \
  --e_layers 2 \
  --enc_in 11 \
  --d_ff 3072 \
  --des 'global_wind' \
  --itr 1 \
  --learning_rate 0.0001 \
  --d_model 768 \
  --batch_size 1 \
  --node_num 3850 \
  --n_heads 16

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/global_wind/ \
  --data_path None \
  --model_id global_wind_48_12_iTransformer \
  --model iTransformer \
  --data Global_Wind \
  --features M \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 12 \
  --e_layers 2 \
  --enc_in 11 \
  --d_ff 3072 \
  --des 'global_wind' \
  --itr 1 \
  --learning_rate 0.0001 \
  --d_model 768 \
  --batch_size 1 \
  --node_num 3850 \
  --n_heads 16

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/global_wind/ \
  --data_path None \
  --model_id global_wind_48_18_iTransformer \
  --model iTransformer \
  --data Global_Wind \
  --features M \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 18 \
  --e_layers 2 \
  --enc_in 11 \
  --d_ff 3072 \
  --des 'global_wind' \
  --itr 1 \
  --learning_rate 0.0001 \
  --d_model 768 \
  --batch_size 1 \
  --node_num 3850 \
  --n_heads 16

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/global_wind/ \
  --data_path None \
  --model_id global_wind_48_24_iTransformer \
  --model iTransformer \
  --data Global_Wind \
  --features M \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 24 \
  --e_layers 2 \
  --enc_in 11 \
  --d_ff 3072 \
  --des 'global_wind' \
  --itr 1 \
  --learning_rate 0.0001 \
  --d_model 768 \
  --batch_size 1 \
  --node_num 3850 \
  --n_heads 16
